metadata.format.version = "1.1"

[versions]

velocity = "3.4.0-SNAPSHOT"
paper = "1.21.8-R0.1-SNAPSHOT"

blossom = "2.1.0"
runtask = "3.0.2"

miniplaceholders = "3.1.0"
luckperms = "5.5"
adventure = "4.25.0"

[libraries]

miniplaceholders = { group = "io.github.miniplaceholders", name = "miniplaceholders-api", version.ref = "miniplaceholders" }
luckperms = { module = "net.luckperms:api", version.ref = "luckperms" }

adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventure-minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure" }
adventure-legacy = { group = "net.kyori", name = "adventure-text-serializer-legacy", version.ref = "adventure" }

[plugins]

blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
runvelocity = { id = "xyz.jpenilla.run-velocity", version.ref = "runtask" }
runpaper = { id = "xyz.jpenilla.run-velocity", version.ref = "runtask" }
idea-ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version = "1.3" }
